# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNTO8Vmmg-HTGCDVBpY9TKkliZXpTI_p
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('Airplane_Crashes_and_Fatalities_Since_1908.csv')
df.head()

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

df.tail(75)

df.shape

df.tail

df.isnull().sum()

df.isnull().sum()
df.info()

(df.isnull().sum() / len(df)) * 100

# 5.Create a new dataframe from the raw/uncleaned data called ‘fatality_locations’
# with columns: Date, Location, Aboard, Fatalities..

import pandas as pd # Import pandas in case it's not globally available yet.

# This cell assumes 'df' has been loaded and defined by a previous cell (e.g., cell tSwY5NTUly3B).
# Please ensure the cell loading the main DataFrame 'df' is run before this cell.

fatality_locations = df[['Date', 'Location', 'Aboard', 'Fatalities']].copy()
print("First 5 rows of 'fatality_locations' dataframe:")
display(fatality_locations.head())

from google.colab import drive
drive.mount('/content/drive')

# 6 Determine the date of the highest number of recorded fatalitie from the new dataframe
#This assumes 'fatality_locations' has been created by the previous cell.

date_highest_fatalities = fatality_locations.loc[fatality_locations['Fatalities'].idxmax(), 'Date']
print(f"The date of the highest number of recorded fatalities is: {date_highest_fatalities}")

# 7. Identify crashes with no fatalities and count them.
zero_fatalities = fatality_locations[fatality_locations['Fatalities'] == 0]
zero_fatalities_count = len(zero_fatalities)
print(f"Number of recorded crashes with no fatalities: {zero_fatalities_count}")

"""From the `fatality_locations` DataFrame, there are **58** recorded crashes where there were no fatalities."""

display(zero_fatalities.head())

fatality_locations['Location'].head(20)

# Split the 'Location' column by the first comma
split_location = fatality_locations['Location'].str.split(',', n=1, expand=True)

# Assign 'Region' from the first part of the split
fatality_locations['Region'] = split_location[0].str.strip()

# Assign 'Country' from the second part if it exists, otherwise assign NaN
# Use .get(1) to safely access the second element, which will return None if not present
# Then use .str.strip() and fillna(pd.NA) to handle potential None/NaN values consistently
fatality_locations['Country'] = split_location.get(1).str.strip().fillna(pd.NA)

display(fatality_locations.head(10))

print(f"Number of null values in 'Country' column: {fatality_locations['Country'].isnull().sum()}")

top_100 = fatality_locations.sort_values('Fatalities', ascending=False).head(100)
top_100.head()

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

top25 = fatality_locations.groupby('Country')['Fatalities'].sum().sort_values(ascending=False).head(25)

plt.figure(figsize=(10,10))
plt.pie(top25, labels=top25.index, autopct='%1.1f%%')
plt.title('Top 25 Countries by Total Fatalities')
plt.show()

"""### Distribution of Fatalities

Let's visualize the distribution of the 'Fatalities' column to understand the spread and frequency of different fatality counts.
"""

plt.figure(figsize=(12, 6))
sns.histplot(fatality_locations['Fatalities'].dropna(), bins=50, kde=True)
plt.title('Distribution of Fatalities in Airplane Crashes')
plt.xlabel('Number of Fatalities')
plt.ylabel('Number of Crashes')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### Top 25 Regions by Total Fatalities

Now, let's look at which regions have experienced the highest number of total fatalities.
"""

top_regions = fatality_locations.groupby('Region')['Fatalities'].sum().sort_values(ascending=False).head(25)

plt.figure(figsize=(12, 8))
sns.barplot(x=top_regions.index, y=top_regions.values, palette='viridis')
plt.title('Top 25 Regions by Total Fatalities')
plt.xlabel('Region')
plt.ylabel('Total Fatalities')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

